title: Robert's notes
email: robert.weclawski@mykolab.com
excerpt_separator: "<!--more-->"
description: > 

baseurl: ""
url: ""
twitter_username: rweclawski
github_username:  robertwe

wakatime:
  username: robertwe
  charts:
    - f7fd7872-30f5-4701-b15b-3cdc484abd5d

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
comments: true

custom:
  comments :
    provider : disqus
    disqus :
      short_name : robertwe

theme: jekyll-theme-slate

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

google_analytics: UA-50640818-1
