title: Robert's notes
email: robert.weclawski@mykolab.com
excerpt_separator: "<!--more-->"
description: >
  Notes on Go, Kubernetes, Terraform/OpenTofu, AWS and DevOps culture -
  written by Robert, a software developer automating things since 2011.

baseurl: "/"
url: "https://roberts-notes.blog"
github_username:  robertwe
linkedin_username: robertweclawski
stackoverflow_username: 213377
wakatime:
  username: robertwe
  charts:
    - 022cbd76-226a-4505-afa7-0afb5af864c5

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - nginx
  - firebase.json
  - node_modules
  - vendor
comments: true

theme: jekyll-whiteglass

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

google_analytics: G-WY8Y4X9RJF
